from User import User
from LinkedList import LinkedList
from Node import Node
from Network import Network
from Stack import Stack
def main():
    # user1=User("jack")
    # user1.addGenre("Thriller")
    # user1.addGenre("Comedy")
    # user1.addGenre("Sci-Fi")
    # user1.displayUser()
    # user1.addBooksRead("Harry Potter and The Prisonor of Azkaban")
    # user1.addBooksRead("Betrayed")
    # user1.displayUser()
    # user1.deleteBooksRead("betrayed")
    # user1.addBooksCurrentlyReading("The Inner Circle")
    # user1.addBooksToBeRead("How The Light Gets In")
    # user1.displayUser()
    # user1.changeName("Jacques")
    # user1.displayUser()
    # user2=User("Mary")
    # user2.displayUser()
    # user1.deleteGenre("sci-Fi")
    # user1.displayUser()
    # user1.deleteUser()
    # user3=User("Ali")
    # user3.displayUser()
    # user4=User("ahmed")
    # user4.displayUser()
    l=LinkedList()
    user1=User("jack")
    user2=User("Mary")
    user3=User("Ali")
    user1.addGenre("Drama")
    user1.addGenre("Romance")
    user2.addGenre("Thriller")
    user2.addGenre("Drama")
    user3.addGenre("Romance")
    user3.addGenre("Sci-fi")
    user4=User("Samah")
    user5=User("Akram")
    user4.addGenre("Romance")
    user4.addGenre("Drama")
    net= Network()
    net.addVertex(user1)
    net.addVertex(user2)
    net.addVertex(user3)
    net.addVertex(user4)
    net.addVertex(user5)
    net.displayNetwork()
    net.addConnection(user1,user2)
    net.addConnection(user2,user5)
    net.displayNetwork()
    net.addConnection(user2,user3)
    net.addConnection(user3,user4)
    net.displayNetwork()
    net.dfs(user1)
    # l.displayNodes()
    # l.addNodeToStart(user1)
    # l.displayNodes()
     
    # l.addNodeToStart(user2)
    # l.addNodeToStart(user3)
    # l.displayNodes()
    # l.removeNode(user2)
    # l.displayNodes()
    # l.removeNode(user1)
    # l.displayNodes()
    # l.removeNode(user3)
    # l.displayNodes()
    # stack = Stack()
    # stack.push(Node(user3))
    # stack.displayNodes()
    # stack.push(Node(user2))
    # print("top is :", stack.top())
    # stack.push(Node(user4))
    # stack.displayNodes()
    # stack.pop()
    # stack.displayNodes()
    # stack.pop()
    # stack.displayNodes()
    # stack.pop()
    # stack.displayNodes()
    # stack.pop()
    # stack.displayNodes()


main()
